### ISSUE TITLE
Image DM does not copy image in test server response

### ISSUE THREAD

**Issue by brandtdamman** [torohangupta/Wall-E#28]
**Describe the bug**  - Please describe the issue here:
When directly messaging an image (with or without additional comments) to Wall-E, the response back to the primary test server simply shows additional comments rather than including the image as well.

**Step to Reproduce** - Steps to reproduce the behavior:

1. Start a DM with Wall-E.
2. Attach image with or without additional comment.
3. Send image.
4. Observe response in test server.

**Expected behavior** - What were you expecting to have happen?:
It is expected that the accompanying image would be sent with the response back to the test server.

**Additional context:**
N/A

**Comment by torohangupta** [comment]
Will be included by default in V2 rewrite. Closing as no-longer planned for current version.

**Comment by torohangupta** [comment]
Will be included by default in V2 rewrite. Closing as no-longer planned for current version.
